name: freeman_portfolio
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.5.beta <3.0.0"

dependencies:
  adaptive_components: ^0.0.7
  animations: ^2.0.3
  auto_route: ^5.0.1
  build_runner: ^2.1.11
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.6.0
  json_serializable: ^6.3.2
  riverpod: ^1.0.3
  url_launcher: ^6.1.4

dev_dependencies:
  auto_route_generator: ^5.0.2

dependency_overrides:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/projects/
    - assets/projects/crackd/
    - assets/projects/githubOAuth/
    - assets/projects/inky/

  fonts:
    - family: Codec Pro
      fonts:
        - asset: assets/fonts/Codec Pro News.ttf
        - asset: assets/fonts/Codec Pro Bold.ttf
          weight: 700