name: freeman_portfolio
description: A personal exploration of Flutter Web's capabilities, crafted into
  this interactive portfolio.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.5.beta <3.0.0"

dependencies:
  analyzer: 5.13.0
  animations: ^2.0.3
  auto_route: ^7.7.0
  build_runner: ^2.1.11
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.6.0
  json_serializable: ^6.3.2
  riverpod: ^1.0.3
  url_launcher: ^6.1.4
  url_strategy: ^0.2.0
  video_player: ^2.6.1

dev_dependencies:
  auto_route_generator: ^7.2.0

dependency_overrides:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/projects/crack'd/
    - assets/projects/ricedrop/
    - assets/projects/glum/
    - assets/projects/inky/
    - assets/projects/oauth2.0/
    - assets/projects/flutterweb/
    - assets/projects/projects.json

  fonts:
    - family: Codec Pro
      fonts:
        - asset: assets/fonts/Codec Pro News.ttf
        - asset: assets/fonts/Codec Pro Bold.ttf
          weight: 700
    - family: RilenoSans
      fonts:
        - asset: assets/fonts/RilenoSans-Regular.otf
        - asset: assets/fonts/RilenoSans-Medium.otf
          weight: 500
        - asset: assets/fonts/RilenoSans-SemiBold.otf
          weight: 700
